{{- if .Values.threeScaleActiveDoc }}

{{- range $threeScaleActiveDocInstance := .Values.threeScaleActiveDoc.instance }}

{{- if $threeScaleActiveDocInstance.extraSpec }}
{{- if $threeScaleActiveDocInstance.extraSpec.openAPIDocument }}
{{- if $threeScaleActiveDocInstance.extraSpec.openAPIDocument.filePath }}
---
apiVersion: v1
kind: Secret
metadata:
  name: activedoc-{{ $threeScaleActiveDocInstance.metadata.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
data:
  activedoc: {{ ($.Files.Get $threeScaleActiveDocInstance.extraSpec.openAPIDocument.filePath) | b64enc }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}

{{- end }}